document.addEventListener('DOMContentLoaded', () => {
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c]));
  const cleanPhone = n => String(n || '').replace(/[^\d+]/g, '');
  const waNumber = n => cleanPhone(n).replace(/^\+/, '').replace(/^0/, '40');
  const siteUrl = location.origin;
  const send = (type, extra = {}) => { try { navigator.sendBeacon('/api/analytics', new Blob([JSON.stringify({ type, path: location.pathname, referrer: document.referrer, ...extra })], { type: 'application/json' })); } catch {} };
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('.nav');
  if (toggle && nav) { toggle.addEventListener('click', () => nav.classList.toggle('open')); nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => nav.classList.remove('open'))); }
  const setLogo = src => document.querySelectorAll('.logo').forEach(el => { const img = document.createElement('img'); img.className = 'brand-logo'; img.src = src || '/content/images/rosini.svg'; img.alt = 'Rosini'; img.onerror = () => { if (img.src.endsWith('/rosini.svg')) return; img.src = '/content/images/rosini.svg'; }; el.textContent = ''; el.appendChild(img); el.setAttribute('aria-label', 'Rosini'); });
  const setPhoneLink = (a, n) => { if (n) { a.href = 'tel:' + cleanPhone(n); a.textContent = n; a.hidden = false; } else a.hidden = true; };
  const setWhatsApp = (a, n, message) => { if (n) { a.href = 'https://wa.me/' + waNumber(n) + '?text=' + encodeURIComponent(message); a.hidden = false; } else a.hidden = true; };
  const renderPhones = s => { const p1 = s.phone_primary || '', p2 = s.phone_secondary || ''; document.querySelectorAll('[data-phone-slot="primary"]').forEach(a => setPhoneLink(a, p1)); document.querySelectorAll('[data-phone-slot="secondary"]').forEach(a => setPhoneLink(a, p2)); document.querySelectorAll('[data-phone-group="primary"]').forEach(g => g.hidden = !p1); document.querySelectorAll('[data-phone-group="secondary"]').forEach(g => g.hidden = !p2); document.querySelectorAll('[data-whatsapp-slot="primary"]').forEach(a => setWhatsApp(a, p1, 'Bună ziua! Doresc să discut despre produsele Rosini.')); document.querySelectorAll('[data-whatsapp-slot="secondary"]').forEach(a => setWhatsApp(a, p2, 'Bună ziua! Doresc să discut despre produsele Rosini.')); document.querySelectorAll('footer .phone-primary').forEach(a => setPhoneLink(a, p1)); document.querySelectorAll('footer .phone-secondary').forEach(a => setPhoneLink(a, p2)); };
  const productPageMap = { 'canapele-living': 'canapele-living-extensie.html', 'canapele-trafic': 'canapele-trafic-intens.html', 'paturi-matrimoniale': 'paturi-matrimoniale.html', 'fotolii': 'fotolii.html', 'tabureti': 'tabureti.html', 'paturi-copii': 'paturi-copii.html', 'mobilier-horeca': 'mobilier-horeca.html' };
  const currentFile = location.pathname.split('/').pop() || 'index.html';
  const currentSlug = Object.keys(productPageMap).find(k => productPageMap[k] === currentFile);
  const configEntries = p => (Array.isArray(p.configuration_options) ? p.configuration_options : []).map((x, i) => { const parts = String(x || '').split(':'); const label = (parts.shift() || ('Configurație ' + (i + 1))).trim(); const opts = parts.join(':').split('|').map(v => v.trim()).filter(Boolean); return { label, opts }; }).filter(x => x.opts.length);
  const selectedConfig = () => [...document.querySelectorAll('.product-config select')].map(s => `${s.dataset.label}: ${s.value}`).filter(Boolean);
  const productMessage = p => { let msg = `Bună ziua! Sunt interesat(ă) de produsul „${p.title}”.`; const cfg = selectedConfig(); if (cfg.length) msg += '\nConfigurație aleasă:\n' + cfg.map(x => '• ' + x).join('\n'); msg += `\nLink produs: ${siteUrl}/${location.pathname.replace(/^\//, '')}`; return msg; };
  function addProductTools(p, s) { const prose = document.querySelector('.prose'); if (!prose || prose.querySelector('.product-tools')) return; const wrap = document.createElement('section'); wrap.className = 'product-tools'; const configs = configEntries(p); wrap.innerHTML = `<div class="section-head"><p class="eyebrow">Configurează</p><h2>Personalizează produsul</h2><p>Alege opțiunile disponibile, apoi trimite configurația direct pe WhatsApp.</p></div>`; if (configs.length) { const box = document.createElement('div'); box.className = 'product-config'; configs.forEach(c => { const label = document.createElement('label'); label.innerHTML = `${esc(c.label)}<select data-label="${esc(c.label)}">${c.opts.map(o => `<option>${esc(o)}</option>`).join('')}</select>`; box.appendChild(label); }); wrap.appendChild(box); } const actions = document.createElement('div'); actions.className = 'actions product-actions'; const p1 = document.createElement('a'); p1.className = 'btn btn-whatsapp'; p1.target = '_blank'; p1.rel = 'noopener'; p1.textContent = 'WhatsApp'; const p2 = document.createElement('a'); p2.className = 'btn btn-whatsapp'; p2.target = '_blank'; p2.rel = 'noopener'; p2.textContent = 'WhatsApp 2'; const c1 = document.createElement('a'); c1.className = 'btn btn-primary'; c1.textContent = 'Sună acum'; const c2 = document.createElement('a'); c2.className = 'btn btn-light'; c2.textContent = 'Sună nr. 2'; actions.append(p1, p2, c1, c2); wrap.appendChild(actions); prose.appendChild(wrap); const update = () => { const msg = productMessage(p); setWhatsApp(p1, s.phone_primary, msg); setWhatsApp(p2, s.phone_secondary, msg); if (s.phone_primary) { c1.href = 'tel:' + cleanPhone(s.phone_primary); c1.hidden = false; } else c1.hidden = true; if (s.phone_secondary) { c2.href = 'tel:' + cleanPhone(s.phone_secondary); c2.hidden = false; } else c2.hidden = true; }; update(); wrap.querySelectorAll('select').forEach(x => x.addEventListener('change', update)); }
  function add360(p) { const imgs = (Array.isArray(p.gallery_360) ? p.gallery_360 : []).map(x => typeof x === 'object' ? x.image : x).filter(Boolean); if (imgs.length < 2) return; const prose = document.querySelector('.prose'); if (!prose || prose.querySelector('.viewer360')) return; const section = document.createElement('section'); section.className = 'viewer360'; section.innerHTML = `<div class="section-head"><p class="eyebrow">360°</p><h2>Vezi produsul din toate unghiurile</h2><p>Glisează cu degetul sau trage cu mouse-ul pentru a roti produsul.</p></div><div class="viewer360-stage"><img alt="${esc(p.title)} — vizualizare 360°"><button type="button" class="viewer360-prev" aria-label="Unghi anterior">‹</button><button type="button" class="viewer360-next" aria-label="Unghi următor">›</button></div><div class="viewer360-hint">${imgs.length} imagini · rotație interactivă</div>`; prose.insertBefore(section, prose.firstChild); const img = section.querySelector('img'); let idx = 0, startX = null; const show = i => { idx = (i + imgs.length) % imgs.length; img.src = imgs[idx]; }; show(0); section.addEventListener('pointerdown', e => { startX = e.clientX; section.setPointerCapture?.(e.pointerId); }); section.addEventListener('pointermove', e => { if (startX === null) return; if (Math.abs(e.clientX - startX) > 18) { show(idx + (e.clientX < startX ? 1 : -1)); startX = e.clientX; } }); section.addEventListener('pointerup', () => startX = null); section.addEventListener('pointercancel', () => startX = null); section.querySelector('.viewer360-prev').onclick = () => show(idx - 1); section.querySelector('.viewer360-next').onclick = () => show(idx + 1); }
  function renderProductCards(grid, products, s) { if (!grid) return; grid.innerHTML = (products || []).map(p => { const href = productPageMap[p.slug] || '#'; const msg = `Bună ziua! Sunt interesat(ă) de produsul „${p.title}”.\nLink produs: ${siteUrl}/${href}`; const wa1 = s.phone_primary ? `https://wa.me/${waNumber(s.phone_primary)}?text=${encodeURIComponent(msg)}` : ''; const wa2 = s.phone_secondary ? `https://wa.me/${waNumber(s.phone_secondary)}?text=${encodeURIComponent(msg)}` : ''; return `<article class="product-card"><a href="${href}"><img src="${esc(p.image || 'https://placehold.co/700x500/png?text=Rosini')}" alt="${esc(p.title)} Rosini"><h3>${esc(p.title)}</h3><span>Vezi produs →</span></a><div class="product-card-actions">${wa1 ? `<a class="btn btn-whatsapp" href="${wa1}" target="_blank" rel="noopener">WhatsApp</a>` : ''}${wa2 ? `<a class="btn btn-whatsapp" href="${wa2}" target="_blank" rel="noopener">WhatsApp 2</a>` : ''}</div></article>`; }).join(''); }
  function renderPortfolio(data) { const grid = document.querySelector('.portfolio-grid'); if (!grid || !Array.isArray(data.portfolio)) return; const items = data.portfolio.filter(x => x.image || x.title); if (!items.length) return; grid.innerHTML = items.map(x => `<article class="portfolio-card"><img src="${esc(x.image || 'https://placehold.co/800x600/png?text=Rosini')}" alt="${esc(x.title || 'Proiect Rosini')}"><div><span>${esc(x.category || 'Proiect')}</span><h3>${esc(x.title || 'Proiect Rosini')}</h3><p>${esc(x.description || '')}</p></div></article>`).join(''); }
  function renderTestimonials(data) { const grid = document.querySelector('.testimonial-grid'); if (!grid || !Array.isArray(data.testimonials)) return; const items = data.testimonials.filter(x => x.body || x.title); if (!items.length) return; grid.innerHTML = items.map(x => `<blockquote><p>${esc(String(x.body || '').replace(/^#+\s*/, '').replace(/[*_]/g, ''))}</p><cite>— ${esc(x.author || x.title || 'Client Rosini')}</cite></blockquote>`).join(''); }
  const reviewForm = document.querySelector('form[name="review"]'); if (reviewForm) reviewForm.addEventListener('submit', e => { if (!reviewForm.checkValidity()) { e.preventDefault(); reviewForm.reportValidity(); } else send('review_submit'); });
  const contactForm = document.querySelector('form[name="contact"]'); if (contactForm) contactForm.addEventListener('submit', e => { if (!contactForm.checkValidity()) { e.preventDefault(); contactForm.reportValidity(); } else send('contact_submit'); });
  document.querySelectorAll('a[href^="tel:"]').forEach(a => a.addEventListener('click', () => send('phone_click'))); document.querySelectorAll('a[href*="wa.me"]').forEach(a => a.addEventListener('click', () => send('whatsapp_click'))); send('page_view');
  fetch('/site-data.json', { cache: 'no-store' }).then(r => r.ok ? r.json() : null).then(data => { if (!data) { setLogo('/content/images/rosini.svg'); return; } const s = data.siteSettings || {}; setLogo(s.logo || '/content/images/rosini.svg'); renderPhones(s); document.querySelectorAll('a[href^="mailto:"]').forEach(a => { if (s.email) { a.href = 'mailto:' + s.email; a.textContent = s.email; } }); document.querySelectorAll('.footer a').forEach(a => { const name = a.textContent.trim(); const url = name === 'Facebook' ? s.facebook_url : name === 'Instagram' ? s.instagram_url : name === 'TikTok' ? s.tiktok_url : ''; if (['Facebook','Instagram','TikTok'].includes(name)) { if (url) { a.href = url; a.target = '_blank'; a.rel = 'noopener'; } else a.parentElement?.remove(); } }); const grid = document.querySelector('.product-grid'); if (grid && Array.isArray(data.categories)) { const categoryParam = new URLSearchParams(location.search).get('category'); if (currentFile === 'produse.html' && categoryParam) { const cat = data.categories.find(c => c.slug === categoryParam); const products = (data.products || []).filter(p => p.category === categoryParam || p.category === cat?.title); const hero = document.querySelector('.page-hero h1'); if (hero) hero.textContent = cat?.title || 'Categorie produse'; if (products.length) renderProductCards(grid, products, s); else grid.innerHTML = `<div class="card"><h3>${esc(cat?.title || 'Categorie')}</h3><p>${esc(cat?.description || 'Produsele din această categorie sunt configurabile din panoul de administrare.')}</p></div>`; } else if (currentFile === 'produse.html') { grid.innerHTML = data.categories.map(c => `<a class="product-card" href="produse.html?category=${encodeURIComponent(c.slug)}"><img src="${esc(c.image || 'https://placehold.co/700x500/png?text=Rosini')}" alt="${esc(c.title)} Rosini"><h3>${esc(c.title)}</h3><span>Vezi categoria →</span></a>`).join(''); } } const p = (data.products || []).find(x => x.slug === currentSlug); if (p) { const h = document.querySelector('.page-hero h1'); if (h) h.textContent = p.title; const hero = document.querySelector('.page-hero p:last-child'); if (hero) hero.textContent = p.description || ''; const img = document.querySelector('.prose img'); if (img && p.image) { img.src = p.image; img.alt = p.title + ' Rosini'; } document.querySelectorAll('.spec').forEach(el => { if (el.textContent.includes('Livrare')) el.innerHTML = '<strong>Livrare</strong>' + (p.delivery_time || ((s.delivery_weeks || 5) + ' săptămâni')); if (el.textContent.includes('Garanție')) el.innerHTML = '<strong>Garanție</strong>' + (p.warranty || ((s.warranty_months || 24) + ' luni')); }); add360(p); addProductTools(p, s); } renderPortfolio(data); renderTestimonials(data); }).catch(() => setLogo('/content/images/rosini.svg'));
});
