import { readdir, readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { join } from 'node:path';
const root = process.cwd(), out = join(root, '_site');
function scalar(v){v=String(v??'').trim();if(!v)return '';if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))return v.slice(1,-1);if(v==='true')return true;if(v==='false')return false;if(/^-?\d+(\.\d+)?$/.test(v))return Number(v);if(v.startsWith('[')&&v.endsWith(']'))return v.slice(1,-1).split(',').map(scalar).filter(v=>v!=='');return v}
function indent(s){return s.match(/^\s*/)?.[0].length??0}
function fm(text){const m=text.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);if(!m)return{data:{},body:text.trim()};const lines=m[1].split(/\r?\n/),data={};let i=0;while(i<lines.length){const raw=lines[i];if(!raw.trim()){i++;continue}if(indent(raw)!==0){i++;continue}const hit=raw.match(/^([^:#][^:]*):\s*(.*)$/);if(!hit){i++;continue}const key=hit[1].trim(),value=hit[2].trim();if(value==='>'||value==='>-'||value==='>- '){i++;const a=[];while(i<lines.length&&(lines[i].trim()===''||indent(lines[i])>0)){if(lines[i].trim())a.push(lines[i].trim());i++}data[key]=a.join(' ').replace(/\s+/g,' ').trim();continue}if(value==='|'||value==='|-'||value==='|+'){i++;const a=[];while(i<lines.length&&(lines[i].trim()===''||indent(lines[i])>0)){a.push(lines[i].replace(/^\s{2}/,''));i++}data[key]=a.join('\n').trim();continue}if(value!==''){data[key]=scalar(value);i++;continue}const next=i+1;if(next>=lines.length||!lines[next].trim()){data[key]='';i++;continue}const ci=indent(lines[next]);if(ci===0){data[key]='';i++;continue}if(lines[next].trim().startsWith('- ')){const list=[];i=next;while(i<lines.length){const line=lines[i];if(!line.trim()){i++;continue}if(indent(line)<ci)break;const im=line.trim().match(/^-\s*(.*)$/);if(!im)break;const t=im[1].trim();if(/^[A-Za-z0-9_-]+:\s*/.test(t)){const obj={},f=t.match(/^([^:]+):\s*(.*)$/);obj[f[1].trim()]=scalar(f[2]);i++;while(i<lines.length&&lines[i].trim()&&indent(lines[i])>ci){const n=lines[i].trim().match(/^([^:]+):\s*(.*)$/);if(n)obj[n[1].trim()]=scalar(n[2]);i++}list.push(obj)}else{list.push(scalar(t));i++}}data[key]=list;continue}const obj={};i=next;while(i<lines.length&&lines[i].trim()&&indent(lines[i])>0){const n=lines[i].trim().match(/^([^:]+):\s*(.*)$/);if(n)obj[n[1].trim()]=scalar(n[2]);i++}data[key]=obj}return{data,body:m[2].trim()}}
async function load(dir){const p=join(root,'content',dir);let names=[];try{names=await readdir(p)}catch{return[]}const result=[];for(const name of names.filter(n=>n.endsWith('.md'))){const parsed=fm(await readFile(join(p,name),'utf8'));result.push({...parsed.data,body:parsed.body,file:name})}return result}
const pages=await load('pages'),products=await load('products'),categories=await load('categories'),testimonials=await load('testimonials'),factory=await load('factory');let siteSettings={};try{siteSettings=fm(await readFile(join(root,'content/site-settings.md'),'utf8')).data}catch{}
await mkdir(out,{recursive:true});for(const entry of await readdir(root,{withFileTypes:true})){if(['_site','.git','node_modules'].includes(entry.name)||entry.name==='site-data.json')continue;await cp(join(root,entry.name),join(out,entry.name),{recursive:true})}
for(const name of await readdir(out)){if(!name.endsWith('.html'))continue;const file=join(out,name);let html=await readFile(file,'utf8');html=html.replace(/<a[^>]+href=[\"']portofoliu\.html[\"'][^>]*>[\s\S]*?<\/a>/gi,'');html=html.replace(/<section[^>]*>[\s\S]*?class=[\"'][^\"']*portfolio-grid[^\"']*[\"'][^>]*>[\s\S]*?<\/section>/gi,'');if(!html.includes('/js/site-enhancements.js'))html=html.replace(/<\/body>/i,'<script src="/js/site-enhancements.js"></script></body>');await writeFile(file,html)}
await writeFile(join(out,'site-data.json'),JSON.stringify({generatedAt:new Date().toISOString(),siteSettings,pages,products,categories,testimonials,factory},null,2));console.log(`Rosini data built: ${categories.length} categorii, ${products.length} produse, ${factory.length} fotografii din fabrică, ${testimonials.length} recenzii.`)
